{"uid":"4f820745e8f39c2f","name":"test_variant_with_ignore_numpy_version_reduces_matrix","fullName":"tests.test_variants#test_variant_with_ignore_numpy_version_reduces_matrix","historyId":"20be92025da8fed1321d1f318c32bbaf","time":{"start":1668033292873,"stop":1668033293499,"duration":626},"status":"skipped","statusMessage":"XFAIL Strange failure 7/19/2017.  Can't reproduce locally.  Test runs fine with parallelism and everything.  Test fails reproducibly on CI, but logging into appveyor after failed run, test passes.  =(\n\nAssertionError: [({'undefined_jinja_vars': [], 'config': <conda_build.config.Config object at 0x000001793392F7F0>, '_meta_path': 'D:\\\\...ld': ['numpy 1.10.*', 'python 3.5.*'], 'run': ['numpy', 'python']}, 'build': {}, 'about': {}}, {...}))])}, True, None)]\nassert 4 == 2\n +  where 4 = len([({'undefined_jinja_vars': [], 'config': <conda_build.config.Config object at 0x000001793392F7F0>, '_meta_path': 'D:\\\\a\\\\conda-build\\\\conda-build\\\\tests\\\\test-recipes\\\\variants\\\\03_numpy_matrix\\\\meta.yaml', '_meta_name': 'meta.yaml', 'path': 'D:\\\\a\\\\conda-build\\\\conda-build\\\\tests\\\\test-recipes\\\\variants\\\\03_numpy_matrix', 'requirements_path': 'D:\\\\a\\\\conda-build\\\\conda-build\\\\tests\\\\test-recipes\\\\variants\\\\03_numpy_matrix\\\\requirements.txt', 'meta': {'package': {'name': 'numpy_matrix', 'version': '1.0'}, 'requirements': {'build': ['python 2.7.*', 'numpy 1.11.*'], 'run': ['python', 'numpy']}, 'extra': {'final': True}, 'build': {}, 'about': {}}, 'type': 'conda', 'other_outputs': OrderedDict([(('numpy_matrix', {'python': '2.7.*', 'numpy': '1.11.*', 'target_platform': 'win-64'}), ({'name': 'numpy_matrix', 'requirements': {'build': ['numpy 1.11.*', 'python 2.7.*'], 'run': ['numpy', 'python']}, 'build': {}, 'about': {}}, {...}))])}, True, None), ({'undefined_jinja_vars': [], 'config': <conda_build.config.Config object at 0x000001792B534D30>, '_meta_path': 'D:\\\\a\\\\conda-build\\\\conda-build\\\\tests\\\\test-recipes\\\\variants\\\\03_numpy_matrix\\\\meta.yaml', '_meta_name': 'meta.yaml', 'path': 'D:\\\\a\\\\conda-build\\\\conda-build\\\\tests\\\\test-recipes\\\\variants\\\\03_numpy_matrix', 'requirements_path': 'D:\\\\a\\\\conda-build\\\\conda-build\\\\tests\\\\test-recipes\\\\variants\\\\03_numpy_matrix\\\\requirements.txt', 'meta': {'package': {'name': 'numpy_matrix', 'version': '1.0'}, 'requirements': {'build': ['python 2.7.*', 'numpy 1.10.*'], 'run': ['python', 'numpy']}, 'extra': {'final': True}, 'build': {}, 'about': {}}, 'type': 'conda', 'other_outputs': OrderedDict([(('numpy_matrix', {'python': '2.7.*', 'numpy': '1.10.*', 'target_platform': 'win-64'}), ({'name': 'numpy_matrix', 'requirements': {'build': ['numpy 1.10.*', 'python 2.7.*'], 'run': ['numpy', 'python']}, 'build': {}, 'about': {}}, {...}))])}, True, None), ({'undefined_jinja_vars': [], 'config': <conda_build.config.Config object at 0x00000179303D1B50>, '_meta_path': 'D:\\\\a\\\\conda-build\\\\conda-build\\\\tests\\\\test-recipes\\\\variants\\\\03_numpy_matrix\\\\meta.yaml', '_meta_name': 'meta.yaml', 'path': 'D:\\\\a\\\\conda-build\\\\conda-build\\\\tests\\\\test-recipes\\\\variants\\\\03_numpy_matrix', 'requirements_path': 'D:\\\\a\\\\conda-build\\\\conda-build\\\\tests\\\\test-recipes\\\\variants\\\\03_numpy_matrix\\\\requirements.txt', 'meta': {'package': {'name': 'numpy_matrix', 'version': '1.0'}, 'requirements': {'build': ['python 3.5.*', 'numpy 1.11.*'], 'run': ['python', 'numpy']}, 'extra': {'final': True}, 'build': {}, 'about': {}}, 'type': 'conda', 'other_outputs': OrderedDict([(('numpy_matrix', {'python': '3.5.*', 'numpy': '1.11.*', 'target_platform': 'win-64'}), ({'name': 'numpy_matrix', 'requirements': {'build': ['numpy 1.11.*', 'python 3.5.*'], 'run': ['numpy', 'python']}, 'build': {}, 'about': {}}, {...}))])}, True, None), ({'undefined_jinja_vars': [], 'config': <conda_build.config.Config object at 0x00000179303D1040>, '_meta_path': 'D:\\\\a\\\\conda-build\\\\conda-build\\\\tests\\\\test-recipes\\\\variants\\\\03_numpy_matrix\\\\meta.yaml', '_meta_name': 'meta.yaml', 'path': 'D:\\\\a\\\\conda-build\\\\conda-build\\\\tests\\\\test-recipes\\\\variants\\\\03_numpy_matrix', 'requirements_path': 'D:\\\\a\\\\conda-build\\\\conda-build\\\\tests\\\\test-recipes\\\\variants\\\\03_numpy_matrix\\\\requirements.txt', 'meta': {'package': {'name': 'numpy_matrix', 'version': '1.0'}, 'requirements': {'build': ['python 3.5.*', 'numpy 1.10.*'], 'run': ['python', 'numpy']}, 'extra': {'final': True}, 'build': {}, 'about': {}}, 'type': 'conda', 'other_outputs': OrderedDict([(('numpy_matrix', {'python': '3.5.*', 'numpy': '1.10.*', 'target_platform': 'win-64'}), ({'name': 'numpy_matrix', 'requirements': {'build': ['numpy 1.10.*', 'python 3.5.*'], 'run': ['numpy', 'python']}, 'build': {}, 'about': {}}, {...}))])}, True, None)])","statusTrace":"Traceback (most recent call last):\n  File \"D:\\a\\conda-build\\conda-build\\tests\\test_variants.py\", line 81, in test_variant_with_ignore_numpy_version_reduces_matrix\n    assert len(metadata) == 2, metadata\nAssertionError: [({'undefined_jinja_vars': [], 'config': <conda_build.config.Config object at 0x000001793392F7F0>, '_meta_path': 'D:\\\\...ld': ['numpy 1.10.*', 'python 3.5.*'], 'run': ['numpy', 'python']}, 'build': {}, 'about': {}}, {...}))])}, True, None)]\nassert 4 == 2\n +  where 4 = len([({'undefined_jinja_vars': [], 'config': <conda_build.config.Config object at 0x000001793392F7F0>, '_meta_path': 'D:\\\\a\\\\conda-build\\\\conda-build\\\\tests\\\\test-recipes\\\\variants\\\\03_numpy_matrix\\\\meta.yaml', '_meta_name': 'meta.yaml', 'path': 'D:\\\\a\\\\conda-build\\\\conda-build\\\\tests\\\\test-recipes\\\\variants\\\\03_numpy_matrix', 'requirements_path': 'D:\\\\a\\\\conda-build\\\\conda-build\\\\tests\\\\test-recipes\\\\variants\\\\03_numpy_matrix\\\\requirements.txt', 'meta': {'package': {'name': 'numpy_matrix', 'version': '1.0'}, 'requirements': {'build': ['python 2.7.*', 'numpy 1.11.*'], 'run': ['python', 'numpy']}, 'extra': {'final': True}, 'build': {}, 'about': {}}, 'type': 'conda', 'other_outputs': OrderedDict([(('numpy_matrix', {'python': '2.7.*', 'numpy': '1.11.*', 'target_platform': 'win-64'}), ({'name': 'numpy_matrix', 'requirements': {'build': ['numpy 1.11.*', 'python 2.7.*'], 'run': ['numpy', 'python']}, 'build': {}, 'about': {}}, {...}))])}, True, None), ({'undefined_jinja_vars': [], 'config': <conda_build.config.Config object at 0x000001792B534D30>, '_meta_path': 'D:\\\\a\\\\conda-build\\\\conda-build\\\\tests\\\\test-recipes\\\\variants\\\\03_numpy_matrix\\\\meta.yaml', '_meta_name': 'meta.yaml', 'path': 'D:\\\\a\\\\conda-build\\\\conda-build\\\\tests\\\\test-recipes\\\\variants\\\\03_numpy_matrix', 'requirements_path': 'D:\\\\a\\\\conda-build\\\\conda-build\\\\tests\\\\test-recipes\\\\variants\\\\03_numpy_matrix\\\\requirements.txt', 'meta': {'package': {'name': 'numpy_matrix', 'version': '1.0'}, 'requirements': {'build': ['python 2.7.*', 'numpy 1.10.*'], 'run': ['python', 'numpy']}, 'extra': {'final': True}, 'build': {}, 'about': {}}, 'type': 'conda', 'other_outputs': OrderedDict([(('numpy_matrix', {'python': '2.7.*', 'numpy': '1.10.*', 'target_platform': 'win-64'}), ({'name': 'numpy_matrix', 'requirements': {'build': ['numpy 1.10.*', 'python 2.7.*'], 'run': ['numpy', 'python']}, 'build': {}, 'about': {}}, {...}))])}, True, None), ({'undefined_jinja_vars': [], 'config': <conda_build.config.Config object at 0x00000179303D1B50>, '_meta_path': 'D:\\\\a\\\\conda-build\\\\conda-build\\\\tests\\\\test-recipes\\\\variants\\\\03_numpy_matrix\\\\meta.yaml', '_meta_name': 'meta.yaml', 'path': 'D:\\\\a\\\\conda-build\\\\conda-build\\\\tests\\\\test-recipes\\\\variants\\\\03_numpy_matrix', 'requirements_path': 'D:\\\\a\\\\conda-build\\\\conda-build\\\\tests\\\\test-recipes\\\\variants\\\\03_numpy_matrix\\\\requirements.txt', 'meta': {'package': {'name': 'numpy_matrix', 'version': '1.0'}, 'requirements': {'build': ['python 3.5.*', 'numpy 1.11.*'], 'run': ['python', 'numpy']}, 'extra': {'final': True}, 'build': {}, 'about': {}}, 'type': 'conda', 'other_outputs': OrderedDict([(('numpy_matrix', {'python': '3.5.*', 'numpy': '1.11.*', 'target_platform': 'win-64'}), ({'name': 'numpy_matrix', 'requirements': {'build': ['numpy 1.11.*', 'python 3.5.*'], 'run': ['numpy', 'python']}, 'build': {}, 'about': {}}, {...}))])}, True, None), ({'undefined_jinja_vars': [], 'config': <conda_build.config.Config object at 0x00000179303D1040>, '_meta_path': 'D:\\\\a\\\\conda-build\\\\conda-build\\\\tests\\\\test-recipes\\\\variants\\\\03_numpy_matrix\\\\meta.yaml', '_meta_name': 'meta.yaml', 'path': 'D:\\\\a\\\\conda-build\\\\conda-build\\\\tests\\\\test-recipes\\\\variants\\\\03_numpy_matrix', 'requirements_path': 'D:\\\\a\\\\conda-build\\\\conda-build\\\\tests\\\\test-recipes\\\\variants\\\\03_numpy_matrix\\\\requirements.txt', 'meta': {'package': {'name': 'numpy_matrix', 'version': '1.0'}, 'requirements': {'build': ['python 3.5.*', 'numpy 1.10.*'], 'run': ['python', 'numpy']}, 'extra': {'final': True}, 'build': {}, 'about': {}}, 'type': 'conda', 'other_outputs': OrderedDict([(('numpy_matrix', {'python': '3.5.*', 'numpy': '1.10.*', 'target_platform': 'win-64'}), ({'name': 'numpy_matrix', 'requirements': {'build': ['numpy 1.10.*', 'python 3.5.*'], 'run': ['numpy', 'python']}, 'build': {}, 'about': {}}, {...}))])}, True, None)])","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"numpy_version_ignored","time":{"start":1668033292873,"stop":1668033292873,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false}],"afterStages":[],"labels":[{"name":"tag","value":"@pytest.mark.xfail(reason='Strange failure 7/19/2017.  Can't reproduce locally.  Test runs fine with parallelism and everything.  Test fails reproducibly on CI, but logging into appveyor after failed run, test passes.  =(')"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_variants"},{"name":"host","value":"fv-az211-563"},{"name":"thread","value":"3484-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_variants"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[],"history":{"statistic":{"failed":0,"broken":0,"skipped":2,"passed":0,"unknown":0,"total":2},"items":[{"uid":"f65b2caef5dc7954","status":"skipped","statusDetails":"XFAIL Strange failure 7/19/2017.  Can't reproduce locally.  Test runs fine with parallelism and everything.  Test fails reproducibly on CI, but logging into appveyor after failed run, test passes.  =(\n\nAssertionError: [({'undefined_jinja_vars': [], 'config': <conda_build.config.Config object at 0x000001793392F7F0>, '_meta_path': 'D:\\\\...ld': ['numpy 1.10.*', 'python 3.5.*'], 'run': ['numpy', 'python']}, 'build': {}, 'about': {}}, {...}))])}, True, None)]\nassert 4 == 2\n +  where 4 = len([({'undefined_jinja_vars': [], 'config': <conda_build.config.Config object at 0x000001793392F7F0>, '_meta_path': 'D:\\\\a\\\\conda-build\\\\conda-build\\\\tests\\\\test-recipes\\\\variants\\\\03_numpy_matrix\\\\meta.yaml', '_meta_name': 'meta.yaml', 'path': 'D:\\\\a\\\\conda-build\\\\conda-build\\\\tests\\\\test-recipes\\\\variants\\\\03_numpy_matrix', 'requirements_path': 'D:\\\\a\\\\conda-build\\\\conda-build\\\\tests\\\\test-recipes\\\\variants\\\\03_numpy_matrix\\\\requirements.txt', 'meta': {'package': {'name': 'numpy_matrix', 'version': '1.0'}, 'requirements': {'build': ['python 2.7.*', 'numpy 1.11.*'], 'run': ['python', 'numpy']}, 'extra': {'final': True}, 'build': {}, 'about': {}}, 'type': 'conda', 'other_outputs': OrderedDict([(('numpy_matrix', {'python': '2.7.*', 'numpy': '1.11.*', 'target_platform': 'win-64'}), ({'name': 'numpy_matrix', 'requirements': {'build': ['numpy 1.11.*', 'python 2.7.*'], 'run': ['numpy', 'python']}, 'build': {}, 'about': {}}, {...}))])}, True, None), ({'undefined_jinja_vars': [], 'config': <conda_build.config.Config object at 0x000001792B534D30>, '_meta_path': 'D:\\\\a\\\\conda-build\\\\conda-build\\\\tests\\\\test-recipes\\\\variants\\\\03_numpy_matrix\\\\meta.yaml', '_meta_name': 'meta.yaml', 'path': 'D:\\\\a\\\\conda-build\\\\conda-build\\\\tests\\\\test-recipes\\\\variants\\\\03_numpy_matrix', 'requirements_path': 'D:\\\\a\\\\conda-build\\\\conda-build\\\\tests\\\\test-recipes\\\\variants\\\\03_numpy_matrix\\\\requirements.txt', 'meta': {'package': {'name': 'numpy_matrix', 'version': '1.0'}, 'requirements': {'build': ['python 2.7.*', 'numpy 1.10.*'], 'run': ['python', 'numpy']}, 'extra': {'final': True}, 'build': {}, 'about': {}}, 'type': 'conda', 'other_outputs': OrderedDict([(('numpy_matrix', {'python': '2.7.*', 'numpy': '1.10.*', 'target_platform': 'win-64'}), ({'name': 'numpy_matrix', 'requirements': {'build': ['numpy 1.10.*', 'python 2.7.*'], 'run': ['numpy', 'python']}, 'build': {}, 'about': {}}, {...}))])}, True, None), ({'undefined_jinja_vars': [], 'config': <conda_build.config.Config object at 0x00000179303D1B50>, '_meta_path': 'D:\\\\a\\\\conda-build\\\\conda-build\\\\tests\\\\test-recipes\\\\variants\\\\03_numpy_matrix\\\\meta.yaml', '_meta_name': 'meta.yaml', 'path': 'D:\\\\a\\\\conda-build\\\\conda-build\\\\tests\\\\test-recipes\\\\variants\\\\03_numpy_matrix', 'requirements_path': 'D:\\\\a\\\\conda-build\\\\conda-build\\\\tests\\\\test-recipes\\\\variants\\\\03_numpy_matrix\\\\requirements.txt', 'meta': {'package': {'name': 'numpy_matrix', 'version': '1.0'}, 'requirements': {'build': ['python 3.5.*', 'numpy 1.11.*'], 'run': ['python', 'numpy']}, 'extra': {'final': True}, 'build': {}, 'about': {}}, 'type': 'conda', 'other_outputs': OrderedDict([(('numpy_matrix', {'python': '3.5.*', 'numpy': '1.11.*', 'target_platform': 'win-64'}), ({'name': 'numpy_matrix', 'requirements': {'build': ['numpy 1.11.*', 'python 3.5.*'], 'run': ['numpy', 'python']}, 'build': {}, 'about': {}}, {...}))])}, True, None), ({'undefined_jinja_vars': [], 'config': <conda_build.config.Config object at 0x00000179303D1040>, '_meta_path': 'D:\\\\a\\\\conda-build\\\\conda-build\\\\tests\\\\test-recipes\\\\variants\\\\03_numpy_matrix\\\\meta.yaml', '_meta_name': 'meta.yaml', 'path': 'D:\\\\a\\\\conda-build\\\\conda-build\\\\tests\\\\test-recipes\\\\variants\\\\03_numpy_matrix', 'requirements_path': 'D:\\\\a\\\\conda-build\\\\conda-build\\\\tests\\\\test-recipes\\\\variants\\\\03_numpy_matrix\\\\requirements.txt', 'meta': {'package': {'name': 'numpy_matrix', 'version': '1.0'}, 'requirements': {'build': ['python 3.5.*', 'numpy 1.10.*'], 'run': ['python', 'numpy']}, 'extra': {'final': True}, 'build': {}, 'about': {}}, 'type': 'conda', 'other_outputs': OrderedDict([(('numpy_matrix', {'python': '3.5.*', 'numpy': '1.10.*', 'target_platform': 'win-64'}), ({'name': 'numpy_matrix', 'requirements': {'build': ['numpy 1.10.*', 'python 3.5.*'], 'run': ['numpy', 'python']}, 'build': {}, 'about': {}}, {...}))])}, True, None)])","time":{"start":1668033292873,"stop":1668033293499,"duration":626}}]},"tags":["@pytest.mark.xfail(reason='Strange failure 7/19/2017.  Can't reproduce locally.  Test runs fine with parallelism and everything.  Test fails reproducibly on CI, but logging into appveyor after failed run, test passes.  =(')"]},"source":"4f820745e8f39c2f.json","parameterValues":[]}