{"uid":"614aef8a9fe2b467","name":"test_variant_with_ignore_numpy_version_reduces_matrix","fullName":"tests.test_variants#test_variant_with_ignore_numpy_version_reduces_matrix","historyId":"20be92025da8fed1321d1f318c32bbaf","time":{"start":1669039480683,"stop":1669039481245,"duration":562},"status":"skipped","statusMessage":"XFAIL Strange failure 7/19/2017.  Can't reproduce locally.  Test runs fine with parallelism and everything.  Test fails reproducibly on CI, but logging into appveyor after failed run, test passes.  =(\n\nAssertionError: [({'undefined_jinja_vars': [], 'config': <conda_build.config.Config object at 0x00000255A0C43CA0>, '_meta_path': 'D:\\\\...ld': ['numpy 1.11.*', 'python 3.5.*'], 'run': ['numpy', 'python']}, 'build': {}, 'about': {}}, {...}))])}, True, None)]\nassert 4 == 2\n +  where 4 = len([({'undefined_jinja_vars': [], 'config': <conda_build.config.Config object at 0x00000255A0C43CA0>, '_meta_path': 'D:\\\\a\\\\conda-build\\\\conda-build\\\\tests\\\\test-recipes\\\\variants\\\\03_numpy_matrix\\\\meta.yaml', '_meta_name': 'meta.yaml', 'path': 'D:\\\\a\\\\conda-build\\\\conda-build\\\\tests\\\\test-recipes\\\\variants\\\\03_numpy_matrix', 'requirements_path': 'D:\\\\a\\\\conda-build\\\\conda-build\\\\tests\\\\test-recipes\\\\variants\\\\03_numpy_matrix\\\\requirements.txt', 'meta': {'package': {'name': 'numpy_matrix', 'version': '1.0'}, 'requirements': {'build': ['python 2.7.*', 'numpy 1.10.*'], 'run': ['python', 'numpy']}, 'extra': {'final': True}, 'build': {}, 'about': {}}, 'type': 'conda', 'other_outputs': OrderedDict([(('numpy_matrix', {'target_platform': 'win-64', 'numpy': '1.10.*', 'python': '2.7.*'}), ({'name': 'numpy_matrix', 'requirements': {'build': ['numpy 1.10.*', 'python 2.7.*'], 'run': ['numpy', 'python']}, 'build': {}, 'about': {}}, {...}))])}, True, None), ({'undefined_jinja_vars': [], 'config': <conda_build.config.Config object at 0x000002559AFE7BB0>, '_meta_path': 'D:\\\\a\\\\conda-build\\\\conda-build\\\\tests\\\\test-recipes\\\\variants\\\\03_numpy_matrix\\\\meta.yaml', '_meta_name': 'meta.yaml', 'path': 'D:\\\\a\\\\conda-build\\\\conda-build\\\\tests\\\\test-recipes\\\\variants\\\\03_numpy_matrix', 'requirements_path': 'D:\\\\a\\\\conda-build\\\\conda-build\\\\tests\\\\test-recipes\\\\variants\\\\03_numpy_matrix\\\\requirements.txt', 'meta': {'package': {'name': 'numpy_matrix', 'version': '1.0'}, 'requirements': {'build': ['python 3.5.*', 'numpy 1.10.*'], 'run': ['python', 'numpy']}, 'extra': {'final': True}, 'build': {}, 'about': {}}, 'type': 'conda', 'other_outputs': OrderedDict([(('numpy_matrix', {'target_platform': 'win-64', 'numpy': '1.10.*', 'python': '3.5.*'}), ({'name': 'numpy_matrix', 'requirements': {'build': ['numpy 1.10.*', 'python 3.5.*'], 'run': ['numpy', 'python']}, 'build': {}, 'about': {}}, {...}))])}, True, None), ({'undefined_jinja_vars': [], 'config': <conda_build.config.Config object at 0x000002559FABAE80>, '_meta_path': 'D:\\\\a\\\\conda-build\\\\conda-build\\\\tests\\\\test-recipes\\\\variants\\\\03_numpy_matrix\\\\meta.yaml', '_meta_name': 'meta.yaml', 'path': 'D:\\\\a\\\\conda-build\\\\conda-build\\\\tests\\\\test-recipes\\\\variants\\\\03_numpy_matrix', 'requirements_path': 'D:\\\\a\\\\conda-build\\\\conda-build\\\\tests\\\\test-recipes\\\\variants\\\\03_numpy_matrix\\\\requirements.txt', 'meta': {'package': {'name': 'numpy_matrix', 'version': '1.0'}, 'requirements': {'build': ['python 2.7.*', 'numpy 1.11.*'], 'run': ['python', 'numpy']}, 'extra': {'final': True}, 'build': {}, 'about': {}}, 'type': 'conda', 'other_outputs': OrderedDict([(('numpy_matrix', {'target_platform': 'win-64', 'numpy': '1.11.*', 'python': '2.7.*'}), ({'name': 'numpy_matrix', 'requirements': {'build': ['numpy 1.11.*', 'python 2.7.*'], 'run': ['numpy', 'python']}, 'build': {}, 'about': {}}, {...}))])}, True, None), ({'undefined_jinja_vars': [], 'config': <conda_build.config.Config object at 0x000002559E926280>, '_meta_path': 'D:\\\\a\\\\conda-build\\\\conda-build\\\\tests\\\\test-recipes\\\\variants\\\\03_numpy_matrix\\\\meta.yaml', '_meta_name': 'meta.yaml', 'path': 'D:\\\\a\\\\conda-build\\\\conda-build\\\\tests\\\\test-recipes\\\\variants\\\\03_numpy_matrix', 'requirements_path': 'D:\\\\a\\\\conda-build\\\\conda-build\\\\tests\\\\test-recipes\\\\variants\\\\03_numpy_matrix\\\\requirements.txt', 'meta': {'package': {'name': 'numpy_matrix', 'version': '1.0'}, 'requirements': {'build': ['python 3.5.*', 'numpy 1.11.*'], 'run': ['python', 'numpy']}, 'extra': {'final': True}, 'build': {}, 'about': {}}, 'type': 'conda', 'other_outputs': OrderedDict([(('numpy_matrix', {'target_platform': 'win-64', 'numpy': '1.11.*', 'python': '3.5.*'}), ({'name': 'numpy_matrix', 'requirements': {'build': ['numpy 1.11.*', 'python 3.5.*'], 'run': ['numpy', 'python']}, 'build': {}, 'about': {}}, {...}))])}, True, None)])","statusTrace":"Traceback (most recent call last):\n  File \"D:\\a\\conda-build\\conda-build\\tests\\test_variants.py\", line 81, in test_variant_with_ignore_numpy_version_reduces_matrix\n    assert len(metadata) == 2, metadata\nAssertionError: [({'undefined_jinja_vars': [], 'config': <conda_build.config.Config object at 0x00000255A0C43CA0>, '_meta_path': 'D:\\\\...ld': ['numpy 1.11.*', 'python 3.5.*'], 'run': ['numpy', 'python']}, 'build': {}, 'about': {}}, {...}))])}, True, None)]\nassert 4 == 2\n +  where 4 = len([({'undefined_jinja_vars': [], 'config': <conda_build.config.Config object at 0x00000255A0C43CA0>, '_meta_path': 'D:\\\\a\\\\conda-build\\\\conda-build\\\\tests\\\\test-recipes\\\\variants\\\\03_numpy_matrix\\\\meta.yaml', '_meta_name': 'meta.yaml', 'path': 'D:\\\\a\\\\conda-build\\\\conda-build\\\\tests\\\\test-recipes\\\\variants\\\\03_numpy_matrix', 'requirements_path': 'D:\\\\a\\\\conda-build\\\\conda-build\\\\tests\\\\test-recipes\\\\variants\\\\03_numpy_matrix\\\\requirements.txt', 'meta': {'package': {'name': 'numpy_matrix', 'version': '1.0'}, 'requirements': {'build': ['python 2.7.*', 'numpy 1.10.*'], 'run': ['python', 'numpy']}, 'extra': {'final': True}, 'build': {}, 'about': {}}, 'type': 'conda', 'other_outputs': OrderedDict([(('numpy_matrix', {'target_platform': 'win-64', 'numpy': '1.10.*', 'python': '2.7.*'}), ({'name': 'numpy_matrix', 'requirements': {'build': ['numpy 1.10.*', 'python 2.7.*'], 'run': ['numpy', 'python']}, 'build': {}, 'about': {}}, {...}))])}, True, None), ({'undefined_jinja_vars': [], 'config': <conda_build.config.Config object at 0x000002559AFE7BB0>, '_meta_path': 'D:\\\\a\\\\conda-build\\\\conda-build\\\\tests\\\\test-recipes\\\\variants\\\\03_numpy_matrix\\\\meta.yaml', '_meta_name': 'meta.yaml', 'path': 'D:\\\\a\\\\conda-build\\\\conda-build\\\\tests\\\\test-recipes\\\\variants\\\\03_numpy_matrix', 'requirements_path': 'D:\\\\a\\\\conda-build\\\\conda-build\\\\tests\\\\test-recipes\\\\variants\\\\03_numpy_matrix\\\\requirements.txt', 'meta': {'package': {'name': 'numpy_matrix', 'version': '1.0'}, 'requirements': {'build': ['python 3.5.*', 'numpy 1.10.*'], 'run': ['python', 'numpy']}, 'extra': {'final': True}, 'build': {}, 'about': {}}, 'type': 'conda', 'other_outputs': OrderedDict([(('numpy_matrix', {'target_platform': 'win-64', 'numpy': '1.10.*', 'python': '3.5.*'}), ({'name': 'numpy_matrix', 'requirements': {'build': ['numpy 1.10.*', 'python 3.5.*'], 'run': ['numpy', 'python']}, 'build': {}, 'about': {}}, {...}))])}, True, None), ({'undefined_jinja_vars': [], 'config': <conda_build.config.Config object at 0x000002559FABAE80>, '_meta_path': 'D:\\\\a\\\\conda-build\\\\conda-build\\\\tests\\\\test-recipes\\\\variants\\\\03_numpy_matrix\\\\meta.yaml', '_meta_name': 'meta.yaml', 'path': 'D:\\\\a\\\\conda-build\\\\conda-build\\\\tests\\\\test-recipes\\\\variants\\\\03_numpy_matrix', 'requirements_path': 'D:\\\\a\\\\conda-build\\\\conda-build\\\\tests\\\\test-recipes\\\\variants\\\\03_numpy_matrix\\\\requirements.txt', 'meta': {'package': {'name': 'numpy_matrix', 'version': '1.0'}, 'requirements': {'build': ['python 2.7.*', 'numpy 1.11.*'], 'run': ['python', 'numpy']}, 'extra': {'final': True}, 'build': {}, 'about': {}}, 'type': 'conda', 'other_outputs': OrderedDict([(('numpy_matrix', {'target_platform': 'win-64', 'numpy': '1.11.*', 'python': '2.7.*'}), ({'name': 'numpy_matrix', 'requirements': {'build': ['numpy 1.11.*', 'python 2.7.*'], 'run': ['numpy', 'python']}, 'build': {}, 'about': {}}, {...}))])}, True, None), ({'undefined_jinja_vars': [], 'config': <conda_build.config.Config object at 0x000002559E926280>, '_meta_path': 'D:\\\\a\\\\conda-build\\\\conda-build\\\\tests\\\\test-recipes\\\\variants\\\\03_numpy_matrix\\\\meta.yaml', '_meta_name': 'meta.yaml', 'path': 'D:\\\\a\\\\conda-build\\\\conda-build\\\\tests\\\\test-recipes\\\\variants\\\\03_numpy_matrix', 'requirements_path': 'D:\\\\a\\\\conda-build\\\\conda-build\\\\tests\\\\test-recipes\\\\variants\\\\03_numpy_matrix\\\\requirements.txt', 'meta': {'package': {'name': 'numpy_matrix', 'version': '1.0'}, 'requirements': {'build': ['python 3.5.*', 'numpy 1.11.*'], 'run': ['python', 'numpy']}, 'extra': {'final': True}, 'build': {}, 'about': {}}, 'type': 'conda', 'other_outputs': OrderedDict([(('numpy_matrix', {'target_platform': 'win-64', 'numpy': '1.11.*', 'python': '3.5.*'}), ({'name': 'numpy_matrix', 'requirements': {'build': ['numpy 1.11.*', 'python 3.5.*'], 'run': ['numpy', 'python']}, 'build': {}, 'about': {}}, {...}))])}, True, None)])","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"numpy_version_ignored","time":{"start":1669039480683,"stop":1669039480683,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false}],"afterStages":[],"labels":[{"name":"tag","value":"@pytest.mark.xfail(reason='Strange failure 7/19/2017.  Can't reproduce locally.  Test runs fine with parallelism and everything.  Test fails reproducibly on CI, but logging into appveyor after failed run, test passes.  =(')"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_variants"},{"name":"host","value":"fv-az171-451"},{"name":"thread","value":"3996-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_variants"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[],"history":{"statistic":{"failed":0,"broken":0,"skipped":2,"passed":0,"unknown":0,"total":2},"items":[{"uid":"cf84f247679631d2","status":"skipped","statusDetails":"XFAIL Strange failure 7/19/2017.  Can't reproduce locally.  Test runs fine with parallelism and everything.  Test fails reproducibly on CI, but logging into appveyor after failed run, test passes.  =(\n\nAssertionError: [({'undefined_jinja_vars': [], 'config': <conda_build.config.Config object at 0x0000017264A76EE0>, '_meta_path': 'D:\\\\...ld': ['numpy 1.11.*', 'python 3.5.*'], 'run': ['numpy', 'python']}, 'build': {}, 'about': {}}, {...}))])}, True, None)]\nassert 4 == 2\n +  where 4 = len([({'undefined_jinja_vars': [], 'config': <conda_build.config.Config object at 0x0000017264A76EE0>, '_meta_path': 'D:\\\\a\\\\conda-build\\\\conda-build\\\\tests\\\\test-recipes\\\\variants\\\\03_numpy_matrix\\\\meta.yaml', '_meta_name': 'meta.yaml', 'path': 'D:\\\\a\\\\conda-build\\\\conda-build\\\\tests\\\\test-recipes\\\\variants\\\\03_numpy_matrix', 'requirements_path': 'D:\\\\a\\\\conda-build\\\\conda-build\\\\tests\\\\test-recipes\\\\variants\\\\03_numpy_matrix\\\\requirements.txt', 'meta': {'package': {'name': 'numpy_matrix', 'version': '1.0'}, 'requirements': {'build': ['python 2.7.*', 'numpy 1.10.*'], 'run': ['python', 'numpy']}, 'extra': {'final': True}, 'build': {}, 'about': {}}, 'type': 'conda', 'other_outputs': OrderedDict([(('numpy_matrix', {'target_platform': 'win-64', 'python': '2.7.*', 'numpy': '1.10.*'}), ({'name': 'numpy_matrix', 'requirements': {'build': ['numpy 1.10.*', 'python 2.7.*'], 'run': ['numpy', 'python']}, 'build': {}, 'about': {}}, {...}))])}, True, None), ({'undefined_jinja_vars': [], 'config': <conda_build.config.Config object at 0x0000017263A9CDF0>, '_meta_path': 'D:\\\\a\\\\conda-build\\\\conda-build\\\\tests\\\\test-recipes\\\\variants\\\\03_numpy_matrix\\\\meta.yaml', '_meta_name': 'meta.yaml', 'path': 'D:\\\\a\\\\conda-build\\\\conda-build\\\\tests\\\\test-recipes\\\\variants\\\\03_numpy_matrix', 'requirements_path': 'D:\\\\a\\\\conda-build\\\\conda-build\\\\tests\\\\test-recipes\\\\variants\\\\03_numpy_matrix\\\\requirements.txt', 'meta': {'package': {'name': 'numpy_matrix', 'version': '1.0'}, 'requirements': {'build': ['python 3.5.*', 'numpy 1.10.*'], 'run': ['python', 'numpy']}, 'extra': {'final': True}, 'build': {}, 'about': {}}, 'type': 'conda', 'other_outputs': OrderedDict([(('numpy_matrix', {'target_platform': 'win-64', 'python': '3.5.*', 'numpy': '1.10.*'}), ({'name': 'numpy_matrix', 'requirements': {'build': ['numpy 1.10.*', 'python 3.5.*'], 'run': ['numpy', 'python']}, 'build': {}, 'about': {}}, {...}))])}, True, None), ({'undefined_jinja_vars': [], 'config': <conda_build.config.Config object at 0x000001726275FD30>, '_meta_path': 'D:\\\\a\\\\conda-build\\\\conda-build\\\\tests\\\\test-recipes\\\\variants\\\\03_numpy_matrix\\\\meta.yaml', '_meta_name': 'meta.yaml', 'path': 'D:\\\\a\\\\conda-build\\\\conda-build\\\\tests\\\\test-recipes\\\\variants\\\\03_numpy_matrix', 'requirements_path': 'D:\\\\a\\\\conda-build\\\\conda-build\\\\tests\\\\test-recipes\\\\variants\\\\03_numpy_matrix\\\\requirements.txt', 'meta': {'package': {'name': 'numpy_matrix', 'version': '1.0'}, 'requirements': {'build': ['python 2.7.*', 'numpy 1.11.*'], 'run': ['python', 'numpy']}, 'extra': {'final': True}, 'build': {}, 'about': {}}, 'type': 'conda', 'other_outputs': OrderedDict([(('numpy_matrix', {'target_platform': 'win-64', 'python': '2.7.*', 'numpy': '1.11.*'}), ({'name': 'numpy_matrix', 'requirements': {'build': ['numpy 1.11.*', 'python 2.7.*'], 'run': ['numpy', 'python']}, 'build': {}, 'about': {}}, {...}))])}, True, None), ({'undefined_jinja_vars': [], 'config': <conda_build.config.Config object at 0x0000017268F9C280>, '_meta_path': 'D:\\\\a\\\\conda-build\\\\conda-build\\\\tests\\\\test-recipes\\\\variants\\\\03_numpy_matrix\\\\meta.yaml', '_meta_name': 'meta.yaml', 'path': 'D:\\\\a\\\\conda-build\\\\conda-build\\\\tests\\\\test-recipes\\\\variants\\\\03_numpy_matrix', 'requirements_path': 'D:\\\\a\\\\conda-build\\\\conda-build\\\\tests\\\\test-recipes\\\\variants\\\\03_numpy_matrix\\\\requirements.txt', 'meta': {'package': {'name': 'numpy_matrix', 'version': '1.0'}, 'requirements': {'build': ['python 3.5.*', 'numpy 1.11.*'], 'run': ['python', 'numpy']}, 'extra': {'final': True}, 'build': {}, 'about': {}}, 'type': 'conda', 'other_outputs': OrderedDict([(('numpy_matrix', {'target_platform': 'win-64', 'python': '3.5.*', 'numpy': '1.11.*'}), ({'name': 'numpy_matrix', 'requirements': {'build': ['numpy 1.11.*', 'python 3.5.*'], 'run': ['numpy', 'python']}, 'build': {}, 'about': {}}, {...}))])}, True, None)])","time":{"start":1668038815148,"stop":1668038815632,"duration":484}}]},"tags":["@pytest.mark.xfail(reason='Strange failure 7/19/2017.  Can't reproduce locally.  Test runs fine with parallelism and everything.  Test fails reproducibly on CI, but logging into appveyor after failed run, test passes.  =(')"]},"source":"614aef8a9fe2b467.json","parameterValues":[]}