[35mDEBUG   [0m urllib3.util.retry:retry.py:594 Incremented Retry for (url='/conda_build_test/win-64/conda_build_test_requirement-1.0-0.tar.bz2'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /conda_build_test/win-64/conda_build_test_requirement-1.0-0.tar.bz2