[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:1007 Starting new HTTPS connection (1): pypi.io:443
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:465 https://pypi.io:443 "GET /packages/source/c/conda_version_test/conda_version_test-0.1.0-1.tar.gz HTTP/1.1" 301 122
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:1007 Starting new HTTPS connection (1): pypi.org:443
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:465 https://pypi.org:443 "GET /packages/source/c/conda_version_test/conda_version_test-0.1.0-1.tar.gz HTTP/1.1" 301 298
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:465 https://files.pythonhosted.org:443 "GET /packages/source/c/conda_version_test/conda_version_test-0.1.0-1.tar.gz HTTP/1.1" 302 0
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:465 https://files.pythonhosted.org:443 "GET /packages/82/81/2de2c0e0a583f65ae0ad11c9697ba3d03b835d57ba4efc55344faaa2cd47/conda_version_test-0.1.0-1.tar.gz HTTP/1.1" 200 11832