{"uid":"b54d950d6f4bfa67","name":"test_variant_with_ignore_numpy_version_reduces_matrix","fullName":"tests.test_variants#test_variant_with_ignore_numpy_version_reduces_matrix","historyId":"20be92025da8fed1321d1f318c32bbaf","time":{"start":1669037073642,"stop":1669037073977,"duration":335},"status":"skipped","statusMessage":"XFAIL Strange failure 7/19/2017.  Can't reproduce locally.  Test runs fine with parallelism and everything.  Test fails reproducibly on CI, but logging into appveyor after failed run, test passes.  =(\n\nAssertionError: [({'undefined_jinja_vars': [], 'config': <conda_build.config.Config object at 0x7f0690f43950>, '_meta_path': '/home/ru...mkl', 'numpy 1.10.*', 'python 3.5.*'], 'run': ['numpy', 'python']}, 'build': {}, 'about': {}}, {...}))])}, True, None)]\nassert 4 == 2\n +  where 4 = len([({'undefined_jinja_vars': [], 'config': <conda_build.config.Config object at 0x7f0690f43950>, '_meta_path': '/home/runner/work/conda-build/conda-build/tests/test-recipes/variants/03_numpy_matrix/meta.yaml', '_meta_name': 'meta.yaml', 'path': '/home/runner/work/conda-build/conda-build/tests/test-recipes/variants/03_numpy_matrix', 'requirements_path': '/home/runner/work/conda-build/conda-build/tests/test-recipes/variants/03_numpy_matrix/requirements.txt', 'meta': {'package': {'name': 'numpy_matrix', 'version': '1.0'}, 'requirements': {'build': ['python 2.7.*', 'numpy 1.11.*', 'nomkl'], 'run': ['python', 'numpy']}, 'extra': {'final': True}, 'build': {}, 'about': {}}, 'type': 'conda', 'other_outputs': OrderedDict([(('numpy_matrix', {'python': '2.7.*', 'target_platform': 'linux-64', 'numpy': '1.11.*'}), ({'name': 'numpy_matrix', 'requirements': {'build': ['nomkl', 'numpy 1.11.*', 'python 2.7.*'], 'run': ['numpy', 'python']}, 'build': {}, 'about': {}}, {...}))])}, True, None), ({'undefined_jinja_vars': [], 'config': <conda_build.config.Config object at 0x7f0683f3ef10>, '_meta_path': '/home/runner/work/conda-build/conda-build/tests/test-recipes/variants/03_numpy_matrix/meta.yaml', '_meta_name': 'meta.yaml', 'path': '/home/runner/work/conda-build/conda-build/tests/test-recipes/variants/03_numpy_matrix', 'requirements_path': '/home/runner/work/conda-build/conda-build/tests/test-recipes/variants/03_numpy_matrix/requirements.txt', 'meta': {'package': {'name': 'numpy_matrix', 'version': '1.0'}, 'requirements': {'build': ['python 3.5.*', 'numpy 1.11.*', 'nomkl'], 'run': ['python', 'numpy']}, 'extra': {'final': True}, 'build': {}, 'about': {}}, 'type': 'conda', 'other_outputs': OrderedDict([(('numpy_matrix', {'python': '3.5.*', 'target_platform': 'linux-64', 'numpy': '1.11.*'}), ({'name': 'numpy_matrix', 'requirements': {'build': ['nomkl', 'numpy 1.11.*', 'python 3.5.*'], 'run': ['numpy', 'python']}, 'build': {}, 'about': {}}, {...}))])}, True, None), ({'undefined_jinja_vars': [], 'config': <conda_build.config.Config object at 0x7f0683f27b90>, '_meta_path': '/home/runner/work/conda-build/conda-build/tests/test-recipes/variants/03_numpy_matrix/meta.yaml', '_meta_name': 'meta.yaml', 'path': '/home/runner/work/conda-build/conda-build/tests/test-recipes/variants/03_numpy_matrix', 'requirements_path': '/home/runner/work/conda-build/conda-build/tests/test-recipes/variants/03_numpy_matrix/requirements.txt', 'meta': {'package': {'name': 'numpy_matrix', 'version': '1.0'}, 'requirements': {'build': ['python 2.7.*', 'numpy 1.10.*', 'nomkl'], 'run': ['python', 'numpy']}, 'extra': {'final': True}, 'build': {}, 'about': {}}, 'type': 'conda', 'other_outputs': OrderedDict([(('numpy_matrix', {'python': '2.7.*', 'target_platform': 'linux-64', 'numpy': '1.10.*'}), ({'name': 'numpy_matrix', 'requirements': {'build': ['nomkl', 'numpy 1.10.*', 'python 2.7.*'], 'run': ['numpy', 'python']}, 'build': {}, 'about': {}}, {...}))])}, True, None), ({'undefined_jinja_vars': [], 'config': <conda_build.config.Config object at 0x7f0688a75f90>, '_meta_path': '/home/runner/work/conda-build/conda-build/tests/test-recipes/variants/03_numpy_matrix/meta.yaml', '_meta_name': 'meta.yaml', 'path': '/home/runner/work/conda-build/conda-build/tests/test-recipes/variants/03_numpy_matrix', 'requirements_path': '/home/runner/work/conda-build/conda-build/tests/test-recipes/variants/03_numpy_matrix/requirements.txt', 'meta': {'package': {'name': 'numpy_matrix', 'version': '1.0'}, 'requirements': {'build': ['python 3.5.*', 'numpy 1.10.*', 'nomkl'], 'run': ['python', 'numpy']}, 'extra': {'final': True}, 'build': {}, 'about': {}}, 'type': 'conda', 'other_outputs': OrderedDict([(('numpy_matrix', {'python': '3.5.*', 'target_platform': 'linux-64', 'numpy': '1.10.*'}), ({'name': 'numpy_matrix', 'requirements': {'build': ['nomkl', 'numpy 1.10.*', 'python 3.5.*'], 'run': ['numpy', 'python']}, 'build': {}, 'about': {}}, {...}))])}, True, None)])","statusTrace":"Traceback (most recent call last):\n  File \"/home/runner/work/conda-build/conda-build/tests/test_variants.py\", line 81, in test_variant_with_ignore_numpy_version_reduces_matrix\n    assert len(metadata) == 2, metadata\nAssertionError: [({'undefined_jinja_vars': [], 'config': <conda_build.config.Config object at 0x7f0690f43950>, '_meta_path': '/home/ru...mkl', 'numpy 1.10.*', 'python 3.5.*'], 'run': ['numpy', 'python']}, 'build': {}, 'about': {}}, {...}))])}, True, None)]\nassert 4 == 2\n +  where 4 = len([({'undefined_jinja_vars': [], 'config': <conda_build.config.Config object at 0x7f0690f43950>, '_meta_path': '/home/runner/work/conda-build/conda-build/tests/test-recipes/variants/03_numpy_matrix/meta.yaml', '_meta_name': 'meta.yaml', 'path': '/home/runner/work/conda-build/conda-build/tests/test-recipes/variants/03_numpy_matrix', 'requirements_path': '/home/runner/work/conda-build/conda-build/tests/test-recipes/variants/03_numpy_matrix/requirements.txt', 'meta': {'package': {'name': 'numpy_matrix', 'version': '1.0'}, 'requirements': {'build': ['python 2.7.*', 'numpy 1.11.*', 'nomkl'], 'run': ['python', 'numpy']}, 'extra': {'final': True}, 'build': {}, 'about': {}}, 'type': 'conda', 'other_outputs': OrderedDict([(('numpy_matrix', {'python': '2.7.*', 'target_platform': 'linux-64', 'numpy': '1.11.*'}), ({'name': 'numpy_matrix', 'requirements': {'build': ['nomkl', 'numpy 1.11.*', 'python 2.7.*'], 'run': ['numpy', 'python']}, 'build': {}, 'about': {}}, {...}))])}, True, None), ({'undefined_jinja_vars': [], 'config': <conda_build.config.Config object at 0x7f0683f3ef10>, '_meta_path': '/home/runner/work/conda-build/conda-build/tests/test-recipes/variants/03_numpy_matrix/meta.yaml', '_meta_name': 'meta.yaml', 'path': '/home/runner/work/conda-build/conda-build/tests/test-recipes/variants/03_numpy_matrix', 'requirements_path': '/home/runner/work/conda-build/conda-build/tests/test-recipes/variants/03_numpy_matrix/requirements.txt', 'meta': {'package': {'name': 'numpy_matrix', 'version': '1.0'}, 'requirements': {'build': ['python 3.5.*', 'numpy 1.11.*', 'nomkl'], 'run': ['python', 'numpy']}, 'extra': {'final': True}, 'build': {}, 'about': {}}, 'type': 'conda', 'other_outputs': OrderedDict([(('numpy_matrix', {'python': '3.5.*', 'target_platform': 'linux-64', 'numpy': '1.11.*'}), ({'name': 'numpy_matrix', 'requirements': {'build': ['nomkl', 'numpy 1.11.*', 'python 3.5.*'], 'run': ['numpy', 'python']}, 'build': {}, 'about': {}}, {...}))])}, True, None), ({'undefined_jinja_vars': [], 'config': <conda_build.config.Config object at 0x7f0683f27b90>, '_meta_path': '/home/runner/work/conda-build/conda-build/tests/test-recipes/variants/03_numpy_matrix/meta.yaml', '_meta_name': 'meta.yaml', 'path': '/home/runner/work/conda-build/conda-build/tests/test-recipes/variants/03_numpy_matrix', 'requirements_path': '/home/runner/work/conda-build/conda-build/tests/test-recipes/variants/03_numpy_matrix/requirements.txt', 'meta': {'package': {'name': 'numpy_matrix', 'version': '1.0'}, 'requirements': {'build': ['python 2.7.*', 'numpy 1.10.*', 'nomkl'], 'run': ['python', 'numpy']}, 'extra': {'final': True}, 'build': {}, 'about': {}}, 'type': 'conda', 'other_outputs': OrderedDict([(('numpy_matrix', {'python': '2.7.*', 'target_platform': 'linux-64', 'numpy': '1.10.*'}), ({'name': 'numpy_matrix', 'requirements': {'build': ['nomkl', 'numpy 1.10.*', 'python 2.7.*'], 'run': ['numpy', 'python']}, 'build': {}, 'about': {}}, {...}))])}, True, None), ({'undefined_jinja_vars': [], 'config': <conda_build.config.Config object at 0x7f0688a75f90>, '_meta_path': '/home/runner/work/conda-build/conda-build/tests/test-recipes/variants/03_numpy_matrix/meta.yaml', '_meta_name': 'meta.yaml', 'path': '/home/runner/work/conda-build/conda-build/tests/test-recipes/variants/03_numpy_matrix', 'requirements_path': '/home/runner/work/conda-build/conda-build/tests/test-recipes/variants/03_numpy_matrix/requirements.txt', 'meta': {'package': {'name': 'numpy_matrix', 'version': '1.0'}, 'requirements': {'build': ['python 3.5.*', 'numpy 1.10.*', 'nomkl'], 'run': ['python', 'numpy']}, 'extra': {'final': True}, 'build': {}, 'about': {}}, 'type': 'conda', 'other_outputs': OrderedDict([(('numpy_matrix', {'python': '3.5.*', 'target_platform': 'linux-64', 'numpy': '1.10.*'}), ({'name': 'numpy_matrix', 'requirements': {'build': ['nomkl', 'numpy 1.10.*', 'python 3.5.*'], 'run': ['numpy', 'python']}, 'build': {}, 'about': {}}, {...}))])}, True, None)])","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"numpy_version_ignored","time":{"start":1669037073641,"stop":1669037073641,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"hasContent":false,"stepsCount":0,"attachmentsCount":0}],"afterStages":[],"labels":[{"name":"tag","value":"@pytest.mark.xfail(reason='Strange failure 7/19/2017.  Can't reproduce locally.  Test runs fine with parallelism and everything.  Test fails reproducibly on CI, but logging into appveyor after failed run, test passes.  =(')"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_variants"},{"name":"host","value":"fv-az626-399"},{"name":"thread","value":"3558-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_variants"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[],"history":{"statistic":{"failed":0,"broken":0,"skipped":2,"passed":0,"unknown":0,"total":2},"items":[{"uid":"305e471d488551aa","status":"skipped","statusDetails":"XFAIL Strange failure 7/19/2017.  Can't reproduce locally.  Test runs fine with parallelism and everything.  Test fails reproducibly on CI, but logging into appveyor after failed run, test passes.  =(\n\nAssertionError: [({'undefined_jinja_vars': [], 'config': <conda_build.config.Config object at 0x7f567f37fb50>, '_meta_path': '/home/ru...mkl', 'numpy 1.11.*', 'python 3.5.*'], 'run': ['numpy', 'python']}, 'build': {}, 'about': {}}, {...}))])}, True, None)]\nassert 4 == 2\n +  where 4 = len([({'undefined_jinja_vars': [], 'config': <conda_build.config.Config object at 0x7f567f37fb50>, '_meta_path': '/home/runner/work/conda-build/conda-build/tests/test-recipes/variants/03_numpy_matrix/meta.yaml', '_meta_name': 'meta.yaml', 'path': '/home/runner/work/conda-build/conda-build/tests/test-recipes/variants/03_numpy_matrix', 'requirements_path': '/home/runner/work/conda-build/conda-build/tests/test-recipes/variants/03_numpy_matrix/requirements.txt', 'meta': {'package': {'name': 'numpy_matrix', 'version': '1.0'}, 'requirements': {'build': ['python 2.7.*', 'numpy 1.10.*', 'nomkl'], 'run': ['python', 'numpy']}, 'extra': {'final': True}, 'build': {}, 'about': {}}, 'type': 'conda', 'other_outputs': OrderedDict([(('numpy_matrix', {'target_platform': 'linux-64', 'numpy': '1.10.*', 'python': '2.7.*'}), ({'name': 'numpy_matrix', 'requirements': {'build': ['nomkl', 'numpy 1.10.*', 'python 2.7.*'], 'run': ['numpy', 'python']}, 'build': {}, 'about': {}}, {...}))])}, True, None), ({'undefined_jinja_vars': [], 'config': <conda_build.config.Config object at 0x7f56947c5850>, '_meta_path': '/home/runner/work/conda-build/conda-build/tests/test-recipes/variants/03_numpy_matrix/meta.yaml', '_meta_name': 'meta.yaml', 'path': '/home/runner/work/conda-build/conda-build/tests/test-recipes/variants/03_numpy_matrix', 'requirements_path': '/home/runner/work/conda-build/conda-build/tests/test-recipes/variants/03_numpy_matrix/requirements.txt', 'meta': {'package': {'name': 'numpy_matrix', 'version': '1.0'}, 'requirements': {'build': ['python 2.7.*', 'numpy 1.11.*', 'nomkl'], 'run': ['python', 'numpy']}, 'extra': {'final': True}, 'build': {}, 'about': {}}, 'type': 'conda', 'other_outputs': OrderedDict([(('numpy_matrix', {'target_platform': 'linux-64', 'numpy': '1.11.*', 'python': '2.7.*'}), ({'name': 'numpy_matrix', 'requirements': {'build': ['nomkl', 'numpy 1.11.*', 'python 2.7.*'], 'run': ['numpy', 'python']}, 'build': {}, 'about': {}}, {...}))])}, True, None), ({'undefined_jinja_vars': [], 'config': <conda_build.config.Config object at 0x7f567bef48d0>, '_meta_path': '/home/runner/work/conda-build/conda-build/tests/test-recipes/variants/03_numpy_matrix/meta.yaml', '_meta_name': 'meta.yaml', 'path': '/home/runner/work/conda-build/conda-build/tests/test-recipes/variants/03_numpy_matrix', 'requirements_path': '/home/runner/work/conda-build/conda-build/tests/test-recipes/variants/03_numpy_matrix/requirements.txt', 'meta': {'package': {'name': 'numpy_matrix', 'version': '1.0'}, 'requirements': {'build': ['python 3.5.*', 'numpy 1.10.*', 'nomkl'], 'run': ['python', 'numpy']}, 'extra': {'final': True}, 'build': {}, 'about': {}}, 'type': 'conda', 'other_outputs': OrderedDict([(('numpy_matrix', {'target_platform': 'linux-64', 'numpy': '1.10.*', 'python': '3.5.*'}), ({'name': 'numpy_matrix', 'requirements': {'build': ['nomkl', 'numpy 1.10.*', 'python 3.5.*'], 'run': ['numpy', 'python']}, 'build': {}, 'about': {}}, {...}))])}, True, None), ({'undefined_jinja_vars': [], 'config': <conda_build.config.Config object at 0x7f567beed190>, '_meta_path': '/home/runner/work/conda-build/conda-build/tests/test-recipes/variants/03_numpy_matrix/meta.yaml', '_meta_name': 'meta.yaml', 'path': '/home/runner/work/conda-build/conda-build/tests/test-recipes/variants/03_numpy_matrix', 'requirements_path': '/home/runner/work/conda-build/conda-build/tests/test-recipes/variants/03_numpy_matrix/requirements.txt', 'meta': {'package': {'name': 'numpy_matrix', 'version': '1.0'}, 'requirements': {'build': ['python 3.5.*', 'numpy 1.11.*', 'nomkl'], 'run': ['python', 'numpy']}, 'extra': {'final': True}, 'build': {}, 'about': {}}, 'type': 'conda', 'other_outputs': OrderedDict([(('numpy_matrix', {'target_platform': 'linux-64', 'numpy': '1.11.*', 'python': '3.5.*'}), ({'name': 'numpy_matrix', 'requirements': {'build': ['nomkl', 'numpy 1.11.*', 'python 3.5.*'], 'run': ['numpy', 'python']}, 'build': {}, 'about': {}}, {...}))])}, True, None)])","time":{"start":1668036865131,"stop":1668036865498,"duration":367}}]},"tags":["@pytest.mark.xfail(reason='Strange failure 7/19/2017.  Can't reproduce locally.  Test runs fine with parallelism and everything.  Test fails reproducibly on CI, but logging into appveyor after failed run, test passes.  =(')"]},"source":"b54d950d6f4bfa67.json","parameterValues":[]}