[35mDEBUG   [0m conda_index.index:__init__.py:680 found subdirs {'osx-64', 'noarch'}
[35mDEBUG   [0m conda_index.index.sqlitecache:sqlitecache.py:101 CondaIndexCache channel_root=/Users/runner/work/conda-build/conda-build/miniconda/conda-bld, subdir=noarch db_filename=/Users/runner/work/conda-build/conda-build/miniconda/conda-bld/noarch/.cache/cache.db cache_is_brand_new=False
[35mDEBUG   [0m conda_index.index.sqlitecache:sqlitecache.py:431 noarch listdir
[35mDEBUG   [0m conda_index.index.sqlitecache:sqlitecache.py:450 noarch save fs state
[35mDEBUG   [0m conda_index.index:__init__.py:759 noarch find packages to extract
[35mDEBUG   [0m conda_index.index:__init__.py:771 noarch extract 0 packages
[32mINFO    [0m conda_index.index:__init__.py:801 noarch cached 0 B from 0 packages at 0 B/second
[35mDEBUG   [0m conda_index.index.sqlitecache:sqlitecache.py:101 CondaIndexCache channel_root=/Users/runner/work/conda-build/conda-build/miniconda/conda-bld, subdir=osx-64 db_filename=/Users/runner/work/conda-build/conda-build/miniconda/conda-bld/osx-64/.cache/cache.db cache_is_brand_new=False
[35mDEBUG   [0m conda_index.index.sqlitecache:sqlitecache.py:431 osx-64 listdir
[35mDEBUG   [0m conda_index.index.sqlitecache:sqlitecache.py:450 osx-64 save fs state
[35mDEBUG   [0m conda_index.index:__init__.py:759 osx-64 find packages to extract
[35mDEBUG   [0m conda_index.index:__init__.py:771 osx-64 extract 0 packages
[32mINFO    [0m conda_index.index:__init__.py:801 osx-64 cached 0 B from 0 packages at 0 B/second
[32mINFO    [0m conda_index.index:__init__.py:578 Completed noarch
[32mINFO    [0m conda_index.index:__init__.py:578 Completed osx-64
[35mDEBUG   [0m conda_index.index:__init__.py:680 found subdirs {'osx-64', 'noarch'}
[32mINFO    [0m conda_index.index:__init__.py:653 Channeldata subdir: noarch
[35mDEBUG   [0m conda_index.index:__init__.py:654 noarch read repodata
[35mDEBUG   [0m conda_index.index.sqlitecache:sqlitecache.py:101 CondaIndexCache channel_root=/Users/runner/work/conda-build/conda-build/miniconda/conda-bld, subdir=noarch db_filename=/Users/runner/work/conda-build/conda-build/miniconda/conda-bld/noarch/.cache/cache.db cache_is_brand_new=False
[35mDEBUG   [0m conda_index.index:__init__.py:662 noarch channeldata finished
[32mINFO    [0m conda_index.index:__init__.py:653 Channeldata subdir: osx-64
[35mDEBUG   [0m conda_index.index:__init__.py:654 osx-64 read repodata
[35mDEBUG   [0m conda_index.index.sqlitecache:sqlitecache.py:101 CondaIndexCache channel_root=/Users/runner/work/conda-build/conda-build/miniconda/conda-bld, subdir=osx-64 db_filename=/Users/runner/work/conda-build/conda-build/miniconda/conda-bld/osx-64/.cache/cache.db cache_is_brand_new=False
[35mDEBUG   [0m conda_index.index:__init__.py:662 osx-64 channeldata finished
[35mDEBUG   [0m conda_index.index:__init__.py:1155 _maybe_write /Users/runner/work/conda-build/conda-build/miniconda/conda-bld/index.html to /Users/runner/work/conda-build/conda-build/miniconda/conda-bld/index.html
[35mDEBUG   [0m conda_index.index:__init__.py:670 write channeldata
[35mDEBUG   [0m conda_index.index:__init__.py:1155 _maybe_write /Users/runner/work/conda-build/conda-build/miniconda/conda-bld/channeldata.json to /Users/runner/work/conda-build/conda-build/miniconda/conda-bld/channeldata.json
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:1003 Starting new HTTPS connection (1): fastapi.metacpan.org:443
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:456 https://fastapi.metacpan.org:443 "GET /v1/module/Moo HTTP/1.1" 200 None
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:456 https://fastapi.metacpan.org:443 "GET /v1/release/Moo HTTP/1.1" 200 None
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:1003 Starting new HTTPS connection (1): fastapi.metacpan.org:443
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:456 https://fastapi.metacpan.org:443 "GET /v1/release/Moo HTTP/1.1" 200 None
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:456 https://fastapi.metacpan.org:443 "GET /v1/module/Sub::Quote HTTP/1.1" 200 None
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:456 https://fastapi.metacpan.org:443 "GET /v1/release/Sub-Quote HTTP/1.1" 200 None
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:1003 Starting new HTTPS connection (1): fastapi.metacpan.org:443
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:456 https://fastapi.metacpan.org:443 "GET /v1/release/Sub-Quote HTTP/1.1" 200 None
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:456 https://fastapi.metacpan.org:443 "GET /v1/module/perl HTTP/1.1" 200 None
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:456 https://fastapi.metacpan.org:443 "GET /v1/release/perl HTTP/1.1" 200 None
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:456 https://fastapi.metacpan.org:443 "GET /v1/module/Class::Method::Modifiers HTTP/1.1" 200 None
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:456 https://fastapi.metacpan.org:443 "GET /v1/release/Class-Method-Modifiers HTTP/1.1" 200 None
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:1003 Starting new HTTPS connection (1): fastapi.metacpan.org:443
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:456 https://fastapi.metacpan.org:443 "GET /v1/release/Class-Method-Modifiers HTTP/1.1" 200 None
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:456 https://fastapi.metacpan.org:443 "GET /v1/module/Role::Tiny HTTP/1.1" 200 None
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:456 https://fastapi.metacpan.org:443 "GET /v1/release/Role-Tiny HTTP/1.1" 200 None
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:1003 Starting new HTTPS connection (1): fastapi.metacpan.org:443
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:456 https://fastapi.metacpan.org:443 "GET /v1/release/Role-Tiny HTTP/1.1" 200 None
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:456 https://fastapi.metacpan.org:443 "GET /v1/module/Sub::Defer HTTP/1.1" 200 None
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:1003 Starting new HTTPS connection (1): fastapi.metacpan.org:443
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:456 https://fastapi.metacpan.org:443 "GET /v1/release/Sub-Defer HTTP/1.1" 404 None
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:1003 Starting new HTTPS connection (1): fastapi.metacpan.org:443
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:456 https://fastapi.metacpan.org:443 "GET /v1/module/Sub::Defer HTTP/1.1" 200 None
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:1003 Starting new HTTPS connection (1): cpan.metacpan.org:443
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:456 https://cpan.metacpan.org:443 "GET /authors/id/H/HA/HAARG/CHECKSUMS HTTP/1.1" 200 235058